// This file acts as our mock database. In a real application,
// this data would come from a server API.

const MOCK_PARKS = [
    {
        id: 'park-1',
        name: 'Thunder Valley Motocross',
        location: 'Lakewood, CO',
        shortDescription: 'Pro-level track with challenging jumps and elevation changes.',
        description: 'Thunder Valley is a world-renowned motocross track that hosts a round of the AMA Pro Motocross Championship. It features significant elevation changes, a variety of soil types, and technical sections that will challenge riders of all skill levels. Amenities include ample parking, concessions, and spectator viewing areas.',
        imageUrl: 'https://placehold.co/600x400/334155/FFF?text=Thunder+Valley',
        rating: 4.8,
        reviewCount: 125,
        price: { adult: 45, child: 25 },
        guestLimit: 200,
    },
    {
        id: 'park-2',
        name: 'Fox Raceway',
        location: 'Pala, CA',
        shortDescription: 'Iconic Southern California track with multiple layouts.',
        description: 'Fox Raceway in Pala, California, is a staple of the SoCal moto scene. It offers several tracks, including a main pro track, a vet track, and a kids track, catering to all abilities. The soil is a mix of sand and loam, and the facility is known for its excellent prep and fun, flowing layouts.',
        imageUrl: 'https://placehold.co/600x400/475569/FFF?text=Fox+Raceway',
        rating: 4.6,
        reviewCount: 210,
        price: { adult: 40, child: 20 },
        guestLimit: 300,
    },
    {
        id: 'park-3',
        name: 'RedBud MX',
        location: 'Buchanan, MI',
        shortDescription: "Home of the legendary LaRocco's Leap.",
        description: "REDDDD BUDDDDD! Famous for its incredible atmosphere and a track that riders love, RedBud is a must-visit. The circuit is known for its amazing dirt, massive jumps including the iconic LaRocco's Leap, and a layout that encourages great racing. It's the heart of American motocross.",
        imageUrl: 'https://placehold.co/600x400/64748B/FFF?text=RedBud+MX',
        rating: 4.9,
        reviewCount: 350,
        price: { adult: 50, child: 30 },
        guestLimit: 500,
    },
    {
        id: 'park-4',
        name: 'Washougal MX Park',
        location: 'Washougal, WA',
        shortDescription: 'Beautiful, tree-lined circuit in the Pacific Northwest.',
        description: "Nestled among the tall fir trees of Washington, Washougal is one of the most scenic tracks on the circuit. It's known for its slippery, hard-pack base and the infamous Horsepower Hill. The track offers a unique challenge and a beautiful setting for a day of riding.",
        imageUrl: 'https://placehold.co/600x400/94A3B8/FFF?text=Washougal',
        rating: 4.5,
        reviewCount: 95,
        price: { adult: 35, child: 15 },
        guestLimit: 150,
    },
     {
        id: 'park-5',
        name: 'Gatorback Cycle Park',
        location: 'Alachua, FL',
        shortDescription: 'Historic sandy track in the heart of Florida.',
        description: 'A classic Florida track, Gatorback is famous for its sandy, whooped-out sections and the iconic "Gator Pit" jump. It has hosted countless major amateur and pro events over the decades. The combination of sand and clay provides a challenging and physically demanding ride.',
        imageUrl: 'https://placehold.co/600x400/1E293B/FFF?text=Gatorback',
        rating: 4.4,
        reviewCount: 150,
        price: { adult: 38, child: 18 },
        guestLimit: 250,
    },
    {
        id: 'park-6',
        name: 'High Point Raceway',
        location: 'Mt. Morris, PA',
        shortDescription: 'Classic East Coast track with natural terrain.',
        description: "High Point Raceway offers a classic motocross experience with its natural, rolling hills and off-camber turns. The soil is a rich, dark loam when it's prepped, making for some of the best conditions imaginable. It's a track that rewards technical skill and smart line choices.",
        imageUrl: 'https://placehold.co/600x400/334155/FFF?text=High+Point',
        rating: 4.7,
        reviewCount: 110,
        price: { adult: 42, child: 22 },
        guestLimit: 180,
    },
];

const MOCK_REVIEWS = [
    { id: 'rev-1', parkId: 'park-1', author: { id: 'user-1', name: 'MotoFan22', isAnonymous: false }, rating: 5, title: 'Absolutely epic!', body: "The elevation changes are no joke. Track prep was amazing. Can't wait to go back!", createdAt: '2025-09-15T10:00:00Z' },
    { id: 'rev-2', parkId: 'park-1', author: { id: 'user-2', name: 'Anonymous', isAnonymous: true }, rating: 4, title: 'Challenging but fun', body: 'This track is tough. Not for beginners, but a great challenge if you have some experience. Well worth the price.', createdAt: '2025-09-10T14:30:00Z' },
    { id: 'rev-3', parkId: 'park-3', author: { id: 'user-3', name: 'BraaapLife', isAnonymous: false }, rating: 5, title: 'RED BUUUUD!', body: "The atmosphere is unmatched. LaRocco's Leap is even bigger in person. A bucket list track for sure.", createdAt: '2025-09-12T11:00:00Z' },
    { id: 'rev-4', parkId: 'park-2', author: { id: 'user-4', name: 'SoCalRider', isAnonymous: false }, rating: 4, title: 'Great variety', body: 'Love that they have tracks for all skill levels. My son had a blast on the kids track while I rode the main.', createdAt: '2025-08-20T18:00:00Z' },
    { id: 'rev-5', parkId: 'park-1', author: { id: 'user-5', name: 'Weekend Warrior', isAnonymous: false }, rating: 5, title: 'Best track in Colorado', body: 'Nothing else compares. The view from the top is incredible and the track flows so well.', createdAt: '2025-09-01T09:00:00Z' },
    { id: 'rev-6', parkId: 'park-3', author: { id: 'user-6', name: 'Anonymous', isAnonymous: true }, rating: 5, title: 'Lived up to the hype', body: 'Everything you hear about RedBud is true. The dirt is perfect. The people are great. 10/10 experience.', createdAt: '2025-08-28T16:45:00Z' },
    { id: 'rev-7', parkId: 'park-4', author: { id: 'user-7', name: 'PNW_Rider', isAnonymous: false }, rating: 4, title: 'Slick and technical', body: 'The dirt is super unique here, very hard pack. It makes you a better rider. Beautiful location!', createdAt: '2025-09-18T12:00:00Z' },
    { id: 'rev-8', parkId: 'park-2', author: { id: 'user-8', name: 'MotoMom', isAnonymous: false }, rating: 5, title: 'Family Friendly!', body: 'We come here all the time. The facilities are clean and the different tracks mean there is something for everyone in our family.', createdAt: '2025-09-16T15:00:00Z' },
];
